# Generated by Django 3.2.23 on 2024-02-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ingredientList', models.CharField(max_length=1000)),
                ('categories', models.ManyToManyField(related_name='food', to='menu.Category')),
                ('ingredients', models.ManyToManyField(to='menu.Food')),
            ],
        ),
    ]
