# Generated by Django 3.2.24 on 2024-02-24 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('shortDescription', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('order', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='menu.category')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DishElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.IntegerField()),
                ('categoryElement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='menu.categoryelement')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('shortName', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('type', models.CharField(choices=[('DISH', 'DISH'), ('CATEGORY', 'CATEGORY'), ('INGREDIENT', 'INGREDIENT')], default='INGREDIENT', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=200, null=True)),
                ('categoryElement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='menu.categoryelement')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=50)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FormulaExtraPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('categoryElement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulaExtraPrices', to='menu.categoryelement')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extraPrice', to='menu.food')),
            ],
        ),
        migrations.CreateModel(
            name='FormulaElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('order', models.IntegerField()),
                ('dishElement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.dishelement')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='menu.formula')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FoodElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('isVisible', models.BooleanField(default=True)),
                ('order', models.IntegerField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.food')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='menu.food')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.FloatField()),
                ('includedNumber', models.IntegerField(default=0)),
                ('order', models.IntegerField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extras', to='menu.food')),
            ],
        ),
        migrations.AddField(
            model_name='dishelement',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.food'),
        ),
        migrations.AddField(
            model_name='categoryelement',
            name='extras',
            field=models.ManyToManyField(to='menu.Extra'),
        ),
        migrations.AddField(
            model_name='category',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='menu.restaurant'),
        ),
        migrations.AddConstraint(
            model_name='formulaextraprice',
            constraint=models.UniqueConstraint(fields=('food', 'categoryElement'), name='formula_extra_price'),
        ),
        migrations.AddConstraint(
            model_name='formulaelement',
            constraint=models.UniqueConstraint(fields=('formula', 'dishElement'), name='formula_element_composite_primary_key'),
        ),
        migrations.AddConstraint(
            model_name='formulaelement',
            constraint=models.UniqueConstraint(fields=('formula', 'order'), name='formula_element_unique_element_order'),
        ),
        migrations.AddConstraint(
            model_name='foodelement',
            constraint=models.UniqueConstraint(fields=('parent', 'child'), name='food_element_composite_primary_key'),
        ),
        migrations.AddConstraint(
            model_name='foodelement',
            constraint=models.UniqueConstraint(fields=('parent', 'order'), name='food_element_unique_element_order'),
        ),
        migrations.AddConstraint(
            model_name='extra',
            constraint=models.UniqueConstraint(fields=('food', 'order'), name='food_element_with_price_unique_element_order'),
        ),
        migrations.AddConstraint(
            model_name='dishelement',
            constraint=models.UniqueConstraint(fields=('food', 'categoryElement'), name='dish_element_composite_primary_key'),
        ),
        migrations.AddConstraint(
            model_name='dishelement',
            constraint=models.UniqueConstraint(fields=('categoryElement', 'order'), name='dish_element_unique_element_order'),
        ),
    ]
