# Generated by Django 3.2.23 on 2024-02-12 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('type', models.CharField(choices=[('SEVERALSIZE', 'SEVERALSIZE'), ('FORMULA', 'FORMULA'), ('SIMPLE', 'SIMPLE')], default='SIMPLE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('shortName', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('type', models.CharField(choices=[('DISH', 'DISH'), ('CATEGORY', 'CATEGORY'), ('INGREDIENT', 'INGREDIENT')], default='INGREDIENT', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PriceSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('pizzaMenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.basedish')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.pizzasize')),
            ],
        ),
        migrations.CreateModel(
            name='FoodElementWithPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('includedNumber', models.IntegerField(default=0)),
                ('order', models.IntegerField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extras', to='menu.food')),
            ],
        ),
        migrations.CreateModel(
            name='FoodElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('isVisible', models.BooleanField(default=True)),
                ('order', models.IntegerField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='menu.food')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.food')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='basedish',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='menu.category'),
        ),
        migrations.AddField(
            model_name='basedish',
            name='extras',
            field=models.ManyToManyField(to='menu.FoodElementWithPrice'),
        ),
        migrations.AddField(
            model_name='basedish',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menuDishes', to='menu.food'),
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('basedish_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.basedish')),
                ('starterDishPrice', models.FloatField()),
                ('dishDessertPrice', models.FloatField()),
                ('allPrice', models.FloatField()),
                ('dessert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menuDesserts', to='menu.food')),
                ('starter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menStartes', to='menu.food')),
            ],
            bases=('menu.basedish',),
        ),
        migrations.AddConstraint(
            model_name='foodelement',
            constraint=models.UniqueConstraint(fields=('parent', 'child'), name='composite_primary_key'),
        ),
    ]
