# Generated by Django 3.2.24 on 2024-02-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryelement',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='dishelement',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='formulaelement',
            options={},
        ),
        migrations.AddField(
            model_name='dishelement',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
