# Generated by Django 3.2.23 on 2024-02-12 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodelement',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.food'),
        ),
        migrations.AlterField(
            model_name='foodelement',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='menu.food'),
        ),
        migrations.AddConstraint(
            model_name='foodelement',
            constraint=models.UniqueConstraint(fields=('parent', 'order'), name='unique_element_order'),
        ),
    ]
