# Generated by Django 3.2.24 on 2024-02-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
