# Generated by Django 3.2.24 on 2024-02-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20240220_1935'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dishelement',
            constraint=models.UniqueConstraint(fields=('categoryElement', 'order'), name='dish_element_unique_element_order'),
        ),
    ]
