# Generated by Django 3.2.23 on 2024-02-12 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20240212_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='dessert',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='menuDesserts', to='menu.food'),
        ),
        migrations.AlterField(
            model_name='formula',
            name='starter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='menStartes', to='menu.food'),
        ),
    ]
