# Generated by Django 3.2.24 on 2024-02-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_dishelement_dish_element_unique_element_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishelement',
            name='name',
            field=models.CharField(default='Plat', max_length=200),
            preserve_default=False,
        ),
    ]
