# Generated by Django 3.2.23 on 2024-02-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20240212_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='allPrice',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='formula',
            name='dishDessertPrice',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='formula',
            name='starterDishPrice',
            field=models.FloatField(null=True),
        ),
    ]
