# Generated by Django 3.2.24 on 2024-03-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20240224_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='addrressLink',
            field=models.CharField(default='https://www.google.com/maps/place/Napolizza/@45.0373284,0.3678008,17z/data=!4m6!3m5!1s0x47ff8b556f98d6c5:0x70d9ab37f0c22a0d!8m2!3d45.0373284!4d0.3678008!16s%2Fg%2F11s2ysvpky?hl=fr&entry=ttu', max_length=300),
            preserve_default=False,
        ),
    ]
