# Generated by Django 3.2.23 on 2024-02-12 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20240212_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricesize',
            name='pizzaMenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='menu.basedish'),
        ),
    ]
