# Generated by Django 3.2.24 on 2024-03-02 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_restaurant_addrresslink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='addrressLink',
            new_name='addressLink',
        ),
    ]
