# Generated by Django 3.2.24 on 2024-03-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_rename_addrresslink_restaurant_addresslink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='type',
            field=models.CharField(choices=[('DISH', 'DISH'), ('CATEGORY_I', 'CATEGORY_I'), ('CATEGORY_D', 'CATEGORY_D'), ('INGREDIENT', 'INGREDIENT')], default='INGREDIENT', max_length=20),
        ),
    ]
