# Generated by Django 3.2.23 on 2024-02-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20240212_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedish',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='basedish',
            constraint=models.UniqueConstraint(fields=('category', 'order'), name='base_dish_unique_element_order'),
        ),
    ]
