# Generated by Django 3.2.24 on 2024-03-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_food_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='food',
            name='shortName',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
