# Generated by Django 3.2.24 on 2024-02-14 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20240212_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='number',
            field=models.CharField(default='23JR58J3F95', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basedish',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.food'),
        ),
        migrations.AlterField(
            model_name='category',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='menu.restaurant'),
        ),
    ]
