# Generated by Django 3.2.24 on 2024-02-19 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_auto_20240214_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='short_description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='basedish',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menuDishes', to='menu.food'),
        ),
        migrations.AlterField(
            model_name='category',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='menu.restaurant'),
        ),
    ]
