# Generated by Django 3.2.24 on 2024-02-19 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_auto_20240219_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='short_description',
            new_name='shortDescription',
        ),
    ]
