# Generated by Django 3.2.24 on 2024-02-19 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_rename_short_description_category_shortdescription'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PizzaSize',
            new_name='DishSize',
        ),
    ]
