# Generated by Django 3.2.23 on 2024-02-13 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0007_auto_20240212_2203'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('number', models.CharField(max_length=200)),
                ('creationDate', models.DateTimeField()),
                ('takeOutDate', models.DateTimeField()),
                ('total', models.FloatField()),
                ('state', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('READY', 'READY'), ('WITHDRAWN', 'WITHDRAWN'), ('CANCELLED', 'CANCELLED'), ('FAILED', 'FAILED')], default='PENDING', max_length=20)),
                ('paymentStatus', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PriceFoodElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('content', models.ManyToManyField(to='menu.BaseDish')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='order.order')),
            ],
        ),
    ]
