services:
  db:
    image: postgres
    volumes:
      - ../data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  backend:
    build: ./backend
    image: django-python:latest
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../app/backend:/src
      - ../assets:/src/assets
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db

  frontend:
    build: ./frontend
    image: angular-dev-server:latest
    ports:
      - 4200:4200
    volumes:
      - ../app/frontend:/src



  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html
    depends_on:
      - backend
    restart: always
    command: [nginx, '-g', 'daemon off;']
